name: "test"
replicaCount: 1

images:
  PullSecrets:
    name: momentumacr
  repository: nginx
  tag: "latest"

service:

volume:
  mountPath: /dist/
  secretName: azure-secret
  shareName: momentum/utils

config:
  configmaps: []
