{{- $wave := default "true" .Values.config.autorestart_associated_deployments -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    {{- if $wave }}
    wave.pusher.com/update-on-config-change: "true"
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      {{- range .Values.images.PullSecrets }}
        - name: {{ . }}
      {{- end }}
      serviceAccountName: {{ .Values.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.images.repository }}:{{ .Values.images.tag }}
        imagePullPolicy: {{ default "Always" .Values.images.pullPolicy }}
        {{ if .Values.service -}}
        ports:
          {{- range .Values.service.ports }}
          - name: {{ .name }}
            containerPort: {{ default .port .targetPort }}
            protocol: {{ default "TCP" .protocol }}
          {{- end }}
          {{ end }}
        envFrom:
          {{- range .Values.config.configmaps }}
          - configMapRef:
              name: {{ . }}
            {{- end }}
        {{ if .Values.config.env }}
        env:
          {{- range .Values.config.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
        {{ end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{ if .Values.volume }}
        volumeMounts:
        - name: azure
          mountPath: {{ .Values.volume.mountPath }}
      volumes:
      - name: azure
        azureFile:
          secretName: {{ .Values.volume.secretName }} #azure-secret #SERCRET-NAME
          shareName: {{ .Values.volume.shareName }} #FILE-SHARE-NAME-WITH-PATH-IN-IT
          readOnly: false
      {{ end }}